# Generated by Django 3.1.4 on 2025-06-16 23:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaParametersSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Set the name for this area.', max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(help_text='Set the latitude of the center of this area\n        <br>\n        e.g.<br>\n        Y.YY... (WGS84)\n        <br>\n        It will not be possible to change this field value after the object is saved in the model.\n        ')),
                ('longitude', models.FloatField(help_text='Set the longitude of the center of this area \n        <br>\n        e.g.<br>\n        X.XX... (WGS84)\n        <br>\n        It will not be possible to change this field value after the object is saved in the model.\n        ')),
                ('radius', models.FloatField(help_text='Set the radius [km] that will define the boundary of this area as a circle around the center.\n        <br>\n        It will not be possible to change this field value after the object is saved in the model.')),
            ],
            options={
                'verbose_name': 'set of parameters of area',
                'verbose_name_plural': 'sets of parameters of areas',
                'ordering': ['-radius', 'name'],
                'unique_together': {('latitude', 'longitude', 'radius')},
            },
        ),
        migrations.CreateModel(
            name='SerieParametersSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Set the name for this set of parameters defining a serie.', max_length=256)),
                ('description', models.TextField(blank=True)),
                ('time_horizon', models.DurationField(default=datetime.timedelta(days=1), help_text='\n        Set the time horizon of the serie.<br>\n        The start time of the serie will be equal to: now - time_horizon<br>\n        The end time will be equal to the current time.<br>\n        <br>\n        e.g.<br>\n        1 hour = 0 01:00:00<br>\n        1 day = 1 00:00:00\n        ', verbose_name='time horizon')),
                ('aggregation_period', models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Set the aggregation period of historical datapoints.<br>\n        <br>\n        e.g.<br>\n        1 hour = 0 01:00:00<br>\n        1 day = 1 00:00:00', verbose_name='aggregation period')),
                ('show_serie', models.BooleanField(default=True, help_text='Check this to show the series in the dashboard.', verbose_name='show serie')),
                ('area_parameters_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm_lookup.areaparametersset')),
            ],
            options={
                'verbose_name': 'set of parameters of serie',
                'verbose_name_plural': 'sets of parameters of series',
                'ordering': ['-area_parameters_set__radius', 'area_parameters_set__name'],
                'unique_together': {('area_parameters_set', 'time_horizon', 'aggregation_period')},
            },
        ),
        migrations.CreateModel(
            name='RealtimeDatapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('last_update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_contributing_sensors', models.PositiveIntegerField(null=True)),
                ('PM10_mean', models.FloatField()),
                ('PM25_mean', models.FloatField()),
                ('PM10_mean_cathegory_label', models.TextField()),
                ('PM25_mean_cathegory_label', models.TextField()),
                ('PM10_mean_cathegory', models.CharField(max_length=50)),
                ('PM25_mean_cathegory', models.CharField(max_length=50)),
                ('area_parameters_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pm_lookup.areaparametersset')),
            ],
            options={
                'verbose_name': 'realtime datapoint',
                'verbose_name_plural': 'realtime datapoints',
                'ordering': ['-area_parameters_set__radius', 'area_parameters_set__name'],
            },
        ),
        migrations.CreateModel(
            name='ComputedSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time_values', models.JSONField()),
                ('PM10_mean_values', models.JSONField()),
                ('PM25_mean_values', models.JSONField()),
                ('number_of_contributing_sensors_values', models.JSONField(null=True)),
                ('PM10_graph_div', models.TextField()),
                ('PM25_graph_div', models.TextField()),
                ('serie_parameters_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pm_lookup.serieparametersset')),
            ],
            options={
                'verbose_name': 'computed serie',
                'verbose_name_plural': 'computed series',
                'ordering': ['-serie_parameters_set__area_parameters_set__radius', 'serie_parameters_set__area_parameters_set__name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDatapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('last_update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_contributing_sensors', models.PositiveIntegerField(null=True)),
                ('PM10_mean', models.FloatField()),
                ('PM25_mean', models.FloatField()),
                ('area_parameters_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm_lookup.areaparametersset')),
            ],
            options={
                'verbose_name': 'historical datapoint',
                'verbose_name_plural': 'historical datapoints',
                'ordering': ['-last_update_time', '-area_parameters_set__radius', 'area_parameters_set__name'],
                'unique_together': {('area_parameters_set', 'last_update_time')},
            },
        ),
    ]
