# Generated by Django 2.2.8 on 2020-04-23 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='target_area_input_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('Radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='target_area_output_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PM10_mean', models.FloatField()),
                ('PM25_mean', models.FloatField()),
                ('Last_update_time', models.DateField(default=django.utils.timezone.now)),
                ('n_selected_sensors', models.IntegerField(null=True)),
                ('PM10_n_missing_data', models.IntegerField(null=True)),
                ('PM25_n_missing_data', models.IntegerField(null=True)),
                ('Target_area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm_lookup.target_area_input_data')),
            ],
        ),
    ]
