# Generated by Django 2.2.8 on 2020-06-03 13:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='target_area_input_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, unique=True)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Radius', models.FloatField()),
            ],
            options={
                'ordering': ['-Radius', 'Name'],
            },
        ),
        migrations.CreateModel(
            name='target_area_output_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('PM10_mean', models.FloatField()),
                ('PM25_mean', models.FloatField()),
                ('PM10_quality', models.CharField(max_length=256)),
                ('PM25_quality', models.CharField(max_length=256)),
                ('PM10_cathegory', models.CharField(max_length=256)),
                ('PM25_cathegory', models.CharField(max_length=256)),
                ('n_selected_sensors', models.IntegerField(null=True)),
                ('Target_area_input_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pm_lookup.target_area_input_data')),
            ],
            options={
                'ordering': ['-Target_area_input_data__Radius', 'Target_area_input_data__Name'],
            },
        ),
        migrations.CreateModel(
            name='target_area_history_series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Record_time_values', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('PM10_mean_values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('PM25_mean_values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('PM10_quality_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('PM25_quality_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('PM10_cathegory_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('PM25_cathegory_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('n_selected_sensors_values', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
                ('PM10_graph_div', models.TextField()),
                ('PM25_graph_div', models.TextField()),
                ('Target_area_input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm_lookup.target_area_input_data')),
            ],
            options={
                'ordering': ['-Target_area_input_data__Radius', 'Target_area_input_data__Name'],
            },
        ),
        migrations.CreateModel(
            name='target_area_history_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('PM10_mean', models.FloatField()),
                ('PM25_mean', models.FloatField()),
                ('PM10_quality', models.CharField(max_length=256)),
                ('PM25_quality', models.CharField(max_length=256)),
                ('PM10_cathegory', models.CharField(max_length=256)),
                ('PM25_cathegory', models.CharField(max_length=256)),
                ('n_selected_sensors', models.IntegerField(null=True)),
                ('Target_area_input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm_lookup.target_area_input_data')),
            ],
            options={
                'ordering': ['-Target_area_input_data__Radius', 'Target_area_input_data__Name', '-Last_update_time'],
                'unique_together': {('Target_area_input_data', 'Last_update_time', 'PM10_mean', 'PM25_mean')},
            },
        ),
    ]
