# Generated by Django 3.1.4 on 2025-06-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealtimeDatapoint',
        ),
    ]
