# Generated by Django 2.2.8 on 2020-06-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target_area_history_data',
            options={'ordering': ['-Target_area_input_data__Radius', 'Target_area_input_data__Name', '-Last_update_time']},
        ),
        migrations.AlterModelOptions(
            name='target_area_output_data',
            options={'ordering': ['-Target_area_input_data__Radius', 'Target_area_input_data__Name']},
        ),
    ]
