# Generated by Django 2.2.8 on 2020-06-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='target_area_history_series',
            new_name='target_area_history_serie',
        ),
    ]
