# Generated by Django 2.2.8 on 2020-06-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0002_auto_20200604_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_area_history_serie',
            name='PM10_cathegory_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='target_area_history_serie',
            name='PM10_mean_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='target_area_history_serie',
            name='PM10_quality_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='target_area_history_serie',
            name='PM25_cathegory_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='target_area_history_serie',
            name='PM25_mean_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='target_area_history_serie',
            name='PM25_quality_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='target_area_history_serie',
            name='Record_time_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='target_area_history_serie',
            name='n_selected_sensors_values',
            field=models.TextField(null=True),
        ),
    ]
