# Generated by Django 2.2.8 on 2020-04-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0002_auto_20200423_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_area_output_data',
            name='PM10_cathegory',
            field=models.CharField(default='no data', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target_area_output_data',
            name='PM10_quality',
            field=models.CharField(default='no data', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target_area_output_data',
            name='PM25_cathegory',
            field=models.CharField(default='no data', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target_area_output_data',
            name='PM25_quality',
            field=models.CharField(default='no data', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target_area_input_data',
            name='Name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
