# Generated by Django 2.2.8 on 2020-06-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0003_auto_20200607_0025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='target_area_output_data',
            new_name='target_area_realtime_data',
        ),
    ]
