# Generated by Django 2.2.8 on 2020-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0003_auto_20200425_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_area_output_data',
            name='Latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target_area_output_data',
            name='Longitude',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target_area_output_data',
            name='Radius',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target_area_input_data',
            name='Longitude',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
