# Generated by Django 2.2.8 on 2020-04-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0004_auto_20200425_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_area_input_data',
            name='Longitude',
            field=models.FloatField(),
        ),
    ]
