# Generated by Django 2.2.8 on 2020-06-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0004_auto_20200610_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='target_area_history_serie',
            new_name='target_area_time_serie',
        ),
    ]
