# Generated by Django 2.2.8 on 2020-07-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0005_auto_20200610_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='target_area_daily_time_serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Record_time_values', models.TextField()),
                ('PM10_mean_values', models.TextField()),
                ('PM25_mean_values', models.TextField()),
                ('PM10_quality_values', models.TextField()),
                ('PM25_quality_values', models.TextField()),
                ('PM10_cathegory_values', models.TextField()),
                ('PM25_cathegory_values', models.TextField()),
                ('n_selected_sensors_values', models.TextField(null=True)),
                ('PM10_graph_div', models.TextField()),
                ('PM25_graph_div', models.TextField()),
                ('Target_area_input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm_lookup.target_area_input_data')),
            ],
            options={
                'ordering': ['-Target_area_input_data__Radius', 'Target_area_input_data__Name'],
            },
        ),
    ]
