# Generated by Django 2.2.8 on 2020-05-04 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0005_auto_20200425_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target_area_input_data',
            options={'ordering': ['-Radius', 'Name']},
        ),
        migrations.AlterModelOptions(
            name='target_area_output_data',
            options={'ordering': ['-Radius', 'Target_area_name']},
        ),
        migrations.RemoveField(
            model_name='target_area_output_data',
            name='PM10_n_missing_data',
        ),
        migrations.RemoveField(
            model_name='target_area_output_data',
            name='PM25_n_missing_data',
        ),
        migrations.CreateModel(
            name='target_area_history_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.FloatField(blank=True)),
                ('Latitude', models.FloatField()),
                ('Radius', models.FloatField()),
                ('Last_update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('PM10_mean', models.FloatField()),
                ('PM25_mean', models.FloatField()),
                ('PM10_quality', models.CharField(max_length=256)),
                ('PM25_quality', models.CharField(max_length=256)),
                ('PM10_cathegory', models.CharField(max_length=256)),
                ('PM25_cathegory', models.CharField(max_length=256)),
                ('n_selected_sensors', models.IntegerField(null=True)),
                ('Target_area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm_lookup.target_area_input_data')),
            ],
            options={
                'ordering': ['-Radius', 'Target_area_name', '-Last_update_time'],
            },
        ),
    ]
