# Generated by Django 2.2.8 on 2020-07-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0006_target_area_daily_time_serie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target_area_history_data',
            options={'ordering': ['-Last_update_time', '-Target_area_input_data__Radius', 'Target_area_input_data__Name']},
        ),
    ]
