# Generated by Django 2.2.8 on 2020-07-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_lookup', '0006_DailyAggregatedDatapointsSerie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='HistoricalDatapoints',
            options={'ordering': ['-Last_update_time', '-target_area__Radius', 'target_area__Name']},
        ),
    ]
